CREATE DATABASE IF NOT EXISTS diary CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'diary' IDENTIFIED BY 'diary';
GRANT ALL ON *.* TO diary@'%' IDENTIFIED BY 'diary' WITH GRANT OPTION;

FLUSH PRIVILEGES;